version: '3.4'
services:
  app:
    networks:
      - servicenet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
        preferences:
          - spread: node.id
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 256M
          cpus: '0.1'
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 120s
      update_config:
        order: stop-first  # this service has a volume, so can't use `start-first`

volumes:
    docker-registry-registry-data:
        external:
            name: docker-registry-registry-data


networks:
  servicenet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET}
